name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout output branch
        uses: actions/checkout@v4
        with:
          ref: output

      - name: Generate codeberg snake SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            codeberg-snake.svg?color_snake=%235BA3E8&color_dots=%232D333B,%23E3F2FD,%2390CAF9,%232196F3,%231565C0


      - name: Commit and push generated files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add codeberg-snake.svg
          git commit -m "chore: update snake" || echo "No changes to commit"
          git push origin output
