name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: 0xRakkesh
          outputs: |
            github-snake.svg
            github-snake-dark.svg?palette=codeberg-dark

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update snake"
          file_pattern: |
            github-snake.svg
            github-snake-dark.svg